table DIM_SRE_ENOVA_CERTIFICATE
	lineageTag: 6f2da375-9da1-4325-bcef-fb28eef98d20

	measure CERT_UNTIL_DATE = DATEADD ( DIM_SRE_ENOVA_CERTIFICATE[CERT_DATE], 10, YEAR )
		formatString: General Date
		lineageTag: 058c51d5-8bf2-4424-b426-30ca354f4b14

	column S_PK_DIM_SRE_ENOVA_CERTIFICATE
		dataType: string
		isHidden
		lineageTag: abbd78b5-327a-4f55-b899-517c9d1555f8
		summarizeBy: none
		sourceColumn: S_PK_DIM_SRE_ENOVA_CERTIFICATE

		annotation SummarizationSetBy = Automatic

	column S_DK_CERTIFICATE_NO
		dataType: string
		isHidden
		lineageTag: 7b61ad9d-24cd-4d30-bb47-fcf8ffcee2cd
		summarizeBy: none
		sourceColumn: S_DK_CERTIFICATE_NO

		annotation SummarizationSetBy = Automatic

	column 'Municipality Number'
		dataType: double
		lineageTag: 02fc2eb3-949e-4025-b43d-37864ef21ba4
		summarizeBy: sum
		sourceColumn: K_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Farm Number'
		dataType: double
		lineageTag: 7b90ca83-b54e-4e38-a1c4-cb3c01fb3266
		summarizeBy: sum
		sourceColumn: G_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Parcel Number'
		dataType: double
		lineageTag: f708cfc0-6da9-4497-a453-85be004bb9ae
		summarizeBy: sum
		sourceColumn: B_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Section Number'
		dataType: double
		lineageTag: 68b4d7f0-4c95-45b6-a7f9-f69ba32efca5
		summarizeBy: sum
		sourceColumn: S_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lease Number'
		dataType: double
		lineageTag: 1269dfec-1184-4f49-b438-4a57e1c3cbfd
		summarizeBy: sum
		sourceColumn: F_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Share Number'
		dataType: double
		lineageTag: 22ec7cc2-85ea-46fb-8629-9bbe385fb057
		summarizeBy: sum
		sourceColumn: ANDELSNUMMER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Usage Unit Number'
		dataType: string
		lineageTag: 7f0d633d-2517-4f51-98d3-7c2bbbc0b157
		summarizeBy: none
		sourceColumn: BRUKS_ENHETS_NUMMER

		annotation SummarizationSetBy = Automatic

	column BUILDING_NUMBER
		dataType: double
		lineageTag: febb0bb1-4ecb-42b3-8b6c-6c075f090154
		summarizeBy: sum
		sourceColumn: BUILDING_NUMBER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STREET_ADDRESS
		dataType: string
		lineageTag: 1f896129-425c-4d82-a972-27695f9579b5
		summarizeBy: none
		sourceColumn: STREET_ADDRESS

		annotation SummarizationSetBy = Automatic

	column POSTAL_CODE
		dataType: double
		lineageTag: 55f56d4d-b215-4373-b89c-2370361de7be
		summarizeBy: sum
		sourceColumn: POSTAL_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POSTAL_AREA
		dataType: string
		lineageTag: 577caaec-6c98-45b5-98f0-6efcae206752
		summarizeBy: none
		sourceColumn: POSTAL_AREA

		annotation SummarizationSetBy = Automatic

	column ORGANIZATION_NO
		dataType: double
		lineageTag: 028bd787-15d0-455e-870a-7018298c4518
		summarizeBy: sum
		sourceColumn: ORGANIZATION_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BUILDING_CATEGORY
		dataType: string
		lineageTag: 3afc77c0-a0d3-4078-9091-36a7c9241c55
		summarizeBy: none
		sourceColumn: BUILDING_CATEGORY

		annotation SummarizationSetBy = Automatic

	column BUILDING_TYPE
		dataType: string
		lineageTag: 0afb70ec-3dd5-4271-b8cc-ae8fa268b86c
		summarizeBy: none
		sourceColumn: BUILDING_TYPE

		annotation SummarizationSetBy = Automatic

	column TYPE_OF_BUILDING
		dataType: string
		lineageTag: d040aaae-5420-47c3-af33-13e011971dc1
		summarizeBy: none
		sourceColumn: TYPE_OF_BUILDING

		annotation SummarizationSetBy = Automatic

	column TEK_STANDARD
		dataType: string
		lineageTag: 117f4d32-9363-4438-9c50-8445af241088
		summarizeBy: none
		sourceColumn: TEK_STANDARD

		annotation SummarizationSetBy = Automatic

	column YEAR_BUILT
		dataType: double
		lineageTag: 55bf5da6-300a-4550-b0e2-feede858b3cb
		summarizeBy: sum
		sourceColumn: YEAR_BUILT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENERGY_CHARACTER
		dataType: string
		lineageTag: a7317efa-d947-435e-87bb-118f06d94278
		summarizeBy: none
		sourceColumn: ENERGY_CHARACTER

		annotation SummarizationSetBy = Automatic

	column HEATING_CHARACTER
		dataType: string
		lineageTag: e3739479-08b7-4fbc-9de0-9586e5d64f16
		summarizeBy: none
		sourceColumn: HEATING_CHARACTER

		annotation SummarizationSetBy = Automatic

	column CERT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3183a6de-0a78-4650-a7ac-c727abdd232c
		summarizeBy: none
		sourceColumn: CERT_DATE

		variation Variasjon
			isDefault
			relationship: 20714c42-1be4-49c8-894c-594fb008d8b6
			defaultHierarchy: LocalDateTable_9af9cedd-cae4-42a2-a15d-cc78732b53a0.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VALID_UNTIL_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4336133b-4119-4bfc-b242-03a24e0e324c
		summarizeBy: none
		sourceColumn: VALID_UNTIL_DATE

		variation Variasjon
			isDefault
			relationship: bb4f2dd6-263c-4a92-a609-fccaa072ac07
			defaultHierarchy: LocalDateTable_bd44100e-aac3-46b2-bb62-a0499fe8eb71.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CERTIFICATE_NO
		dataType: string
		lineageTag: 1b4104f5-7451-4d90-9752-1bff6527f827
		summarizeBy: none
		sourceColumn: CERTIFICATE_NO

		annotation SummarizationSetBy = Automatic

	column DATE_LEAKAGE_VALUE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6fac891c-30a7-4a16-9d1a-2b058467add5
		summarizeBy: none
		sourceColumn: DATE_LEAKAGE_VALUE

		variation Variasjon
			isDefault
			relationship: 5acf1acf-45af-4e3c-93b4-d146a4a53d1a
			defaultHierarchy: LocalDateTable_75c469ac-9535-4b5f-979d-7f7e748890d6.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DBT_LAST_LOADED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: f5f93148-f9ff-4c6c-9623-d389486f5c5a
		summarizeBy: none
		sourceColumn: DBT_LAST_LOADED_DATETIME

		variation Variasjon
			isDefault
			relationship: a97340e1-fb13-45bb-aadb-338093d38051
			defaultHierarchy: LocalDateTable_9a4665c4-4d33-47f2-a434-ef631a898f4b.Datohierarki

		annotation SummarizationSetBy = Automatic

	column CERT_UNTIL_DATE_CALC
		dataType: dateTime
		formatString: Long Date
		lineageTag: f32bafb9-c6fe-40df-9d83-cb8f42499c49
		summarizeBy: none
		sourceColumn: CERT_UNTIL_DATE_CALC

		variation Variasjon
			isDefault
			relationship: 7b3026ac-23ba-494c-adef-8351f4d93ed1
			defaultHierarchy: LocalDateTable_e1ccb8fa-26e6-4161-9ced-e20e000583b8.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DIM_SRE_ENOVA_CERTIFICATE = m
		mode: import
		source =
				let
				    Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com","ANALYSIS_SAM_WH",[Implementation="2.0"]),
				    DWH_SAM_Database = Kilde{[Name="DWH_SAM",Kind="Database"]}[Data],
				    REAL_ESTATE_Schema = DWH_SAM_Database{[Name="REAL_ESTATE",Kind="Schema"]}[Data],
				    DIM_SRE_ENOVA_CERTIFICATE_View = REAL_ESTATE_Schema{[Name="DIM_SRE_ENOVA_CERTIFICATE",Kind="View"]}[Data],
				  #"Lagt til egendefinert" = Table.TransformColumnTypes(Table.AddColumn(DIM_SRE_ENOVA_CERTIFICATE_View, "CERT_UNTIL_DATE_CALC", each Date.AddYears([CERT_DATE], 10)), {{"CERT_UNTIL_DATE_CALC", type date}})
				in
				    #"Lagt til egendefinert"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigasjon

