table DIM_SRE_BREEAM_CERTIFICATE
	lineageTag: 2c19235c-00fb-48a5-8796-6567eb6b0133

	column S_PK_DIM_SRE_BREEAM_CERTIFICATE
		dataType: string
		lineageTag: 4bf87016-8b93-4960-969c-7cad0ec71ebe
		summarizeBy: none
		sourceColumn: S_PK_DIM_SRE_BREEAM_CERTIFICATE

		annotation SummarizationSetBy = Automatic

	column S_DK_CERTIFICATE_NO
		dataType: string
		lineageTag: 1701379f-964c-49d0-82cb-68b00b80db6d
		summarizeBy: none
		sourceColumn: S_DK_CERTIFICATE_NO

		annotation SummarizationSetBy = Automatic

	column ASSESSOR_NAME
		dataType: string
		lineageTag: aa1bc549-7803-4625-92db-15ffeb979f5b
		summarizeBy: none
		sourceColumn: ASSESSOR_NAME

		annotation SummarizationSetBy = Automatic

	column BUILDING_NAME
		dataType: string
		lineageTag: 95f86329-1ba7-42ee-b802-9d7aae672e26
		summarizeBy: none
		sourceColumn: BUILDING_NAME

		annotation SummarizationSetBy = Automatic

	column POSTAL_NO
		dataType: double
		lineageTag: 9221e04c-91b5-4863-b74f-8391cda0a276
		summarizeBy: sum
		sourceColumn: POSTAL_NO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STREET_ADDRESS
		dataType: string
		lineageTag: 56814f52-73ae-421b-9b89-9b7892b088c8
		summarizeBy: none
		sourceColumn: STREET_ADDRESS

		annotation SummarizationSetBy = Automatic

	column BUILDING_CATEGORY
		dataType: string
		lineageTag: 2343710b-a607-4139-962b-3efd42a9ffa0
		summarizeBy: none
		sourceColumn: BUILDING_CATEGORY

		annotation SummarizationSetBy = Automatic

	column CERTIFICATE_TYPE
		dataType: string
		lineageTag: 6bc7925e-67af-4b36-9133-0261d6ff5381
		summarizeBy: none
		sourceColumn: CERTIFICATE_TYPE

		annotation SummarizationSetBy = Automatic

	column RATING
		dataType: string
		lineageTag: 0c6eab5b-63fd-4a6a-8c18-f374608b5e0a
		summarizeBy: none
		sourceColumn: RATING

		annotation SummarizationSetBy = Automatic

	column BREEAM_SCHEME
		dataType: string
		lineageTag: 011590d9-0a53-44f0-b829-f4760f9e69a4
		summarizeBy: none
		sourceColumn: BREEAM_SCHEME

		annotation SummarizationSetBy = Automatic

	column CERT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a654816-7d19-4394-a506-1cf0e7bb9e74
		summarizeBy: none
		sourceColumn: CERT_DATE

		variation Variasjon
			isDefault
			relationship: d5c8c9ae-ce6a-4de7-bb7f-970e956f9daf
			defaultHierarchy: LocalDateTable_265afa6e-64d4-4917-8794-300733dbd965.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CERT_UNTIL_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20b066eb-3559-47a8-9e7e-99d29b7cf31b
		summarizeBy: none
		sourceColumn: CERT_UNTIL_DATE

		variation Variasjon
			isDefault
			relationship: 7a64133b-e18f-43f5-b020-07716fd21070
			defaultHierarchy: LocalDateTable_2227d73c-44f8-48d2-8cf5-2e2924fd7a04.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VALID_UNTIL_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8de3c11f-16dc-4f2c-aedd-d9cbaa53da37
		summarizeBy: none
		sourceColumn: VALID_UNTIL_DATE

		variation Variasjon
			isDefault
			relationship: 4af7c809-662c-4787-8e33-05167756b24e
			defaultHierarchy: LocalDateTable_bda8164b-53b6-4866-b9c7-e2cbfb65e162.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DBT_LAST_LOADED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: c9748bb9-3d99-41bc-8d4e-ff353dcf5e61
		summarizeBy: none
		sourceColumn: DBT_LAST_LOADED_DATETIME

		variation Variasjon
			isDefault
			relationship: 8f633aeb-599e-4c6e-a797-7d09f7258403
			defaultHierarchy: LocalDateTable_e9fc460a-36ff-4a15-bfa0-1f9c0f4f7b04.Datohierarki

		annotation SummarizationSetBy = Automatic

	column CERT_UNTIL_DATE_CALC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1290f221-ec2b-419a-80aa-84a59cb20384
		summarizeBy: none
		sourceColumn: CERT_UNTIL_DATE_CALC

		variation Variasjon
			isDefault
			relationship: b4502982-c037-4ebf-a418-b1a6a6850e00
			defaultHierarchy: LocalDateTable_70fdbb3e-c6f3-4350-b5b0-3746393b5081.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DIM_SRE_BREEAM_CERTIFICATE = m
		mode: import
		source =
				let
				    Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com","ANALYSIS_SAM_WH",[Implementation="2.0"]),
				    DEV_DWH_SAM_Database = Kilde{[Name="DWH_SAM",Kind="Database"]}[Data],
				    DBT_95X_REAL_ESTATE_Schema = DEV_DWH_SAM_Database{[Name="REAL_ESTATE",Kind="Schema"]}[Data],
				    DIM_SRE_BREEAM_CERTIFICATE_View = DBT_95X_REAL_ESTATE_Schema{[Name="DIM_SRE_BREEAM_CERTIFICATE",Kind="View"]}[Data],
				  #"Lagt til egendefinert" = Table.TransformColumnTypes(Table.AddColumn(DIM_SRE_BREEAM_CERTIFICATE_View, "CERT_UNTIL_DATE_CALC", each Date.AddYears([CERT_DATE], 3)), {{"CERT_UNTIL_DATE_CALC", type date}})
				in
				    #"Lagt til egendefinert"

	annotation PBI_NavigationStepName = Navigasjon

	annotation PBI_ResultType = Table

