table FACT_SRE_PRODUCT_PERFORMANCE
	lineageTag: 2e43da7a-4fb0-4405-96b9-46800f452f8e

	measure Quarter_DirectReturn_% = ```
			
			VAR CY = [QUARTER_DIRECT_RETURN]
			VAR PY = 
			    CALCULATE(
			        [QUARTER_DIRECT_RETURN],
			        OFFSET(
			            -1,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			VAR _format_CY = FORMAT( CY, "0.00 %;0.00 %" )
			VAR _format_PY = FORMAT( PY, "0.00 %;0.00 %" )
			RETURN
			IF(
			    _perc > 0,
			    _format_CY & " " & UNICHAR(129029) & " (" & _format_PY & ")",
			    IF(
			        _perc < 0,
			        _format_CY & " " & UNICHAR(129031) & " (" & _format_PY & ")",
			        _format_CY & " " & UNICHAR(129030) & " (" & _format_PY & ")"
			    )
			)
			```
		lineageTag: ad29d27f-a57e-4fb0-bf76-eeb223ae3533

	measure QUARTER_DIRECT_RETURN = SUM(FACT_SRE_PRODUCT_PERFORMANCE[DIRECT_RETURN_QUARTER])
		formatString: Percent
		lineageTag: 24aef545-a934-470e-b7f6-4b8e3a06b553

		annotation PBI_FormatHint = {"isCustom":true}

	measure YEAR_DIRECT_RETURN = SUM(FACT_SRE_PRODUCT_PERFORMANCE[DIRECT_RETURN_YEAR])
		formatString: Percent
		lineageTag: 717a6134-cdd9-41de-8eb3-73a7bc8b501a

		annotation PBI_FormatHint = {"isCustom":true}

	measure YEAR_TOTAL_RETURN = SUM(FACT_SRE_PRODUCT_PERFORMANCE[TOTAL_RETURN_YEAR])
		formatString: Percent
		lineageTag: 7cd1f1c5-cc73-4672-9c74-e26f97023ea7

		annotation PBI_FormatHint = {"isCustom":true}

	measure QUARTER_TOTAL_RETURN = SUM(FACT_SRE_PRODUCT_PERFORMANCE[TOTAL_RETURN_QUARTER])
		formatString: Percent
		lineageTag: 7b00eb6e-dbd9-4c1e-83a1-66bff04d2c87

		annotation PBI_FormatHint = {"isCustom":true}

	measure Quarter_DirectReturn_%_ColorFormat = ```
			
			VAR CY = [QUARTER_DIRECT_RETURN]
			VAR PY = 
			    CALCULATE(
			        [QUARTER_DIRECT_RETURN],
			        OFFSET(
			            -1,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			RETURN
			IF(
			    _perc > 0,
			    "Green",
			    IF(
			        _perc < 0,
			        "Red",
			        "Automatic"
			    )
			)
			```
		lineageTag: d3f88114-29cb-4d45-bb41-dd17e58fc1e9

	measure Year_DirectReturn_%_ColorFormat = ```
			
			VAR CY = [YEAR_DIRECT_RETURN]
			VAR PY = 
			    CALCULATE(
			        [YEAR_DIRECT_RETURN],
			        OFFSET(
			            -4,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			RETURN
			IF(
			    _perc > 0,
			    "Green",
			    IF(
			        _perc < 0,
			        "Red",
			        "Automatic"
			    )
			)
			```
		lineageTag: cd1b8c26-3dab-4a12-b840-63a6e2ca3dc4

	measure Year_DirectReturn_% = ```
			
			VAR CY = [YEAR_DIRECT_RETURN]
			VAR PY = 
			    CALCULATE(
			        [YEAR_DIRECT_RETURN],
			        OFFSET(
			            -4,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			VAR _format_CY = FORMAT( CY, "0.00 %;0.00 %" )
			VAR _format_PY = FORMAT( PY, "0.00 %;0.00 %" )
			RETURN
			IF(
			    _perc > 0,
			    _format_CY & " " & UNICHAR(129029) & " (" & _format_PY & ")",
			    IF(
			        _perc < 0,
			        _format_CY & " " & UNICHAR(129031) & " (" & _format_PY & ")",
			        _format_CY & " " & UNICHAR(129030) & " (" & _format_PY & ")"
			    )
			)
			```
		lineageTag: b83a2b2e-5f63-4af9-a122-1e34767eec8b

	measure Year_TotalReturn_% = ```
			
			VAR CY = [YEAR_TOTAL_RETURN]
			VAR PY = 
			    CALCULATE(
			        [YEAR_TOTAL_RETURN],
			        OFFSET(
			            -4,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			VAR _format_CY = FORMAT( CY, "0.00 %;0.00 %" )
			VAR _format_PY = FORMAT( PY, "0.00 %;0.00 %" )
			RETURN
			IF(
			    _perc > 0,
			    _format_CY & " " & UNICHAR(129029) & " (" & _format_PY & ")",
			    IF(
			        _perc < 0,
			        _format_CY & " " & UNICHAR(129031) & " (" & _format_PY & ")",
			        _format_CY & " " & UNICHAR(129030) & " (" & _format_PY & ")"
			    )
			)
			```
		lineageTag: 46c7ab50-7c58-47f5-b52b-60f445db941f

	measure Year_TotalReturn_%_ColorFormat = ```
			
			VAR CY = [YEAR_TOTAL_RETURN]
			VAR PY = 
			    CALCULATE(
			        [YEAR_TOTAL_RETURN],
			        OFFSET(
			            -4,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			RETURN
			IF(
			    _perc > 0,
			    "Green",
			    IF(
			        _perc < 0,
			        "Red",
			        "Automatic"
			    )
			)
			```
		lineageTag: 0bd68879-08e7-4285-a8d1-450d4ed16f0c

	measure Quarter_TotalReturn_% = ```
			
			VAR CY = [QUARTER_TOTAL_RETURN]
			VAR PY = 
			    CALCULATE(
			        [QUARTER_TOTAL_RETURN],
			        OFFSET(
			            -1,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			VAR _format_CY = FORMAT( CY, "0.00 %;0.00 %" )
			VAR _format_PY = FORMAT( PY, "0.00 %;0.00 %" )
			RETURN
			IF(
			    _perc > 0,
			    _format_CY & " " & UNICHAR(129029) & " (" & _format_PY & ")",
			    IF(
			        _perc < 0,
			        _format_CY & " " & UNICHAR(129031) & " (" & _format_PY & ")",
			        _format_CY & " " & UNICHAR(129030) & " (" & _format_PY & ")"
			    )
			)
			```
		lineageTag: ae29d479-f5df-46c1-b155-e3ff818b543d

	measure Quarter_TotalReturn_%_ColorFormat = ```
			
			VAR CY = [QUARTER_TOTAL_RETURN]
			VAR PY = 
			    CALCULATE(
			        [QUARTER_TOTAL_RETURN],
			        OFFSET(
			            -1,
			            ALL(DIM_DATE[FULL_YEAR_QUARTER_NAME]),
			            ORDERBY( DIM_DATE[FULL_YEAR_QUARTER_NAME], ASC)
			        )
			    )
			VAR _perc =  CY-PY
			RETURN
			IF(
			    _perc > 0,
			    "Green",
			    IF(
			        _perc < 0,
			        "Red",
			        "Automatic"
			    )
			)
			```
		lineageTag: 347ed321-2c03-48b9-950f-d66c70b361cf

	column S_PK_FACT_SRE_PRODUCT_PERFORMANCE
		dataType: string
		lineageTag: 922570fc-9500-4887-b423-092068be4340
		summarizeBy: none
		sourceColumn: S_PK_FACT_SRE_PRODUCT_PERFORMANCE

		annotation SummarizationSetBy = Automatic

	column S_DK_SUB_PORTFOLIO_ID
		dataType: string
		lineageTag: a72a33ea-5c54-4257-b6cb-460065c0fdb3
		summarizeBy: none
		sourceColumn: S_DK_SUB_PORTFOLIO_ID

		annotation SummarizationSetBy = Automatic

	column S_DK_PERFORMANCE_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d6157a0-3fb0-469a-8955-46d1b68a7cfb
		summarizeBy: none
		sourceColumn: S_DK_PERFORMANCE_DATE

		variation Variasjon
			isDefault
			relationship: 0e64a3b5-86e0-4d29-bc28-e328ef2bcf18
			defaultHierarchy: LocalDateTable_f89fc23d-ea0b-48cf-be85-fff01a5153b6.Datohierarki

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column S_FK_DIM_SRE_PRODUCT
		dataType: string
		lineageTag: d32d59cb-77a4-4386-95dc-4d916319a640
		summarizeBy: none
		sourceColumn: S_FK_DIM_SRE_PRODUCT

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_DATE_PERFORMANCE_DATE
		dataType: string
		lineageTag: 2e505722-bd0a-4221-9f4a-03d82ccbb308
		summarizeBy: none
		sourceColumn: S_FK_DIM_DATE_PERFORMANCE_DATE

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_CURRENCY
		dataType: string
		lineageTag: 0e926423-5c6f-4edd-a795-a18d9038d7fa
		summarizeBy: none
		sourceColumn: S_FK_DIM_CURRENCY

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_COUNTRY
		dataType: string
		lineageTag: ebd28899-041e-48f1-a912-df49a70aed8f
		summarizeBy: none
		sourceColumn: S_FK_DIM_COUNTRY

		annotation SummarizationSetBy = Automatic

	column CHANGE_IN_VALUE_QUARTER
		dataType: double
		lineageTag: 48f03a08-380c-43a8-a4c1-d6aa386ab284
		summarizeBy: sum
		sourceColumn: CHANGE_IN_VALUE_QUARTER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEBT
		dataType: double
		lineageTag: 807d3e7a-82c2-4f2c-9181-72a8b0429650
		summarizeBy: sum
		sourceColumn: DEBT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIRECT_RETURN_QUARTER
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c2760298-af9f-4c4a-a7e0-342e40bdc943
		summarizeBy: sum
		sourceColumn: DIRECT_RETURN_QUARTER

		annotation SummarizationSetBy = Automatic

	column DIRECT_RETURN_YEAR
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 6ffcfaaa-5159-4c2f-9e2f-1930f1becb11
		summarizeBy: sum
		sourceColumn: DIRECT_RETURN_YEAR

		annotation SummarizationSetBy = Automatic

	column ENTERPRISE_VALUE
		dataType: double
		lineageTag: 9c6f8068-15bb-4201-83dc-e1c6463c9dc9
		summarizeBy: sum
		sourceColumn: ENTERPRISE_VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FINANCE_GAIN_LOSS_QUARTER
		dataType: double
		lineageTag: a7320de1-c1d6-4f6e-93b8-712e171945af
		summarizeBy: sum
		sourceColumn: FINANCE_GAIN_LOSS_QUARTER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PROFIT_LOSS_QUARTER
		dataType: double
		lineageTag: 90c2df9b-c2f8-46c6-ba70-2b88d128d4e0
		summarizeBy: sum
		sourceColumn: PROFIT_LOSS_QUARTER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_RETURN_QUARTER
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 045d56e2-7157-4f12-9943-8f8a20749f4b
		summarizeBy: sum
		sourceColumn: TOTAL_RETURN_QUARTER

		annotation SummarizationSetBy = Automatic

	column TOTAL_RETURN_YEAR
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 126c2e87-055f-4136-a684-e8f126d7bf5b
		summarizeBy: sum
		sourceColumn: TOTAL_RETURN_YEAR

		annotation SummarizationSetBy = Automatic

	column VEK
		dataType: double
		lineageTag: e4c8e160-04ef-467f-9a8c-4123c1437d57
		summarizeBy: sum
		sourceColumn: VEK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_SRE_PRODUCT_PERFORMANCE = m
		mode: import
		source =
				let
				  Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com", "ANALYSIS_SAM_WH", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = "2.0"]),
				  #"Navigering 1" = Kilde{[Name = "DWH_SAM", Kind = "Database"]}[Data],
				  #"Navigering 2" = #"Navigering 1"{[Name = "REAL_ESTATE", Kind = "Schema"]}[Data],
				  #"Navigering 3" = #"Navigering 2"{[Name = "FACT_SRE_PRODUCT_PERFORMANCE", Kind = "View"]}[Data]
				in
				  #"Navigering 3"

	annotation PBI_ResultType = Table

