table Breeam
	lineageTag: 2c19235c-00fb-48a5-8796-6567eb6b0133

	column S_PK_DIM_SRE_BREEAM_CERTIFICATE
		dataType: string
		isHidden
		lineageTag: 4bf87016-8b93-4960-969c-7cad0ec71ebe
		summarizeBy: none
		sourceColumn: S_PK_DIM_SRE_BREEAM_CERTIFICATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Certificate No'
		dataType: string
		lineageTag: 1701379f-964c-49d0-82cb-68b00b80db6d
		summarizeBy: none
		sourceColumn: Certificate No

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Assessor Name'
		dataType: string
		lineageTag: aa1bc549-7803-4625-92db-15ffeb979f5b
		summarizeBy: none
		sourceColumn: Assessor Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Building Name'
		dataType: string
		lineageTag: 95f86329-1ba7-42ee-b802-9d7aae672e26
		summarizeBy: none
		sourceColumn: Building Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: double
		lineageTag: 9221e04c-91b5-4863-b74f-8391cda0a276
		summarizeBy: sum
		sourceColumn: Postal Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Address
		dataType: string
		lineageTag: 56814f52-73ae-421b-9b89-9b7892b088c8
		summarizeBy: none
		sourceColumn: Address

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Building Category'
		dataType: string
		lineageTag: 2343710b-a607-4139-962b-3efd42a9ffa0
		summarizeBy: none
		sourceColumn: Building Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Certificate Type'
		dataType: string
		lineageTag: 6bc7925e-67af-4b36-9133-0261d6ff5381
		summarizeBy: none
		sourceColumn: Certificate Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: string
		lineageTag: 0c6eab5b-63fd-4a6a-8c18-f374608b5e0a
		summarizeBy: none
		sourceColumn: Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Breeam Scheme'
		dataType: string
		lineageTag: 011590d9-0a53-44f0-b829-f4760f9e69a4
		summarizeBy: none
		sourceColumn: Breeam Scheme

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Certification Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a654816-7d19-4394-a506-1cf0e7bb9e74
		summarizeBy: none
		sourceColumn: Certification Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Certification Valid Until Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20b066eb-3559-47a8-9e7e-99d29b7cf31b
		summarizeBy: none
		sourceColumn: Certification Valid Until Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VALID_UNTIL_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8de3c11f-16dc-4f2c-aedd-d9cbaa53da37
		summarizeBy: none
		sourceColumn: VALID_UNTIL_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DBT_LAST_LOADED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c9748bb9-3d99-41bc-8d4e-ff353dcf5e61
		summarizeBy: none
		sourceColumn: DBT_LAST_LOADED_DATETIME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Certification Expiry Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1290f221-ec2b-419a-80aa-84a59cb20384
		summarizeBy: none
		sourceColumn: Certification Expiry Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition Breeam = m
		mode: import
		source =
				let
				    Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com","ANALYSIS_SAM_WH",[Implementation="2.0"]),
				    DEV_DWH_SAM_Database = Kilde{[Name="DWH_SAM",Kind="Database"]}[Data],
				    DBT_95X_REAL_ESTATE_Schema = DEV_DWH_SAM_Database{[Name="REAL_ESTATE",Kind="Schema"]}[Data],
				    DIM_SRE_BREEAM_CERTIFICATE_View = DBT_95X_REAL_ESTATE_Schema{[Name="DIM_SRE_BREEAM_CERTIFICATE",Kind="View"]}[Data],
				  #"Lagt til egendefinert" = Table.TransformColumnTypes(Table.AddColumn(DIM_SRE_BREEAM_CERTIFICATE_View, "CERT_UNTIL_DATE_CALC", each Date.AddYears([CERT_DATE], 3)), {{"CERT_UNTIL_DATE_CALC", type date}}),
				    #"Kolonner med nye navn" = Table.RenameColumns(#"Lagt til egendefinert",{{"RATING", "Rating"}, {"ASSESSOR_NAME", "Assessor Name"}, {"BREEAM_SCHEME", "Breeam Scheme"}, {"BUILDING_CATEGORY", "Building Category"}, {"BUILDING_NAME", "Building Name"}, {"STREET_ADDRESS", "Address"}, {"S_DK_CERTIFICATE_NO", "Certificate No"}, {"CERT_UNTIL_DATE_CALC", "Certification Expiry Date"}, {"CERT_DATE", "Certification Date"}, {"CERT_UNTIL_DATE", "Certification Valid Until Date"}, {"POSTAL_NO", "Postal Code"}, {"CERTIFICATE_TYPE", "Certificate Type"}})
				in
				    #"Kolonner med nye navn"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigasjon

	annotation PBI_ResultType = Table

