table FACT_SRE_PRODUCT_PERFORMANCE
	isHidden
	lineageTag: 2e43da7a-4fb0-4405-96b9-46800f452f8e

	column S_PK_FACT_SRE_PRODUCT_PERFORMANCE
		dataType: string
		isHidden
		lineageTag: 922570fc-9500-4887-b423-092068be4340
		summarizeBy: none
		sourceColumn: S_PK_FACT_SRE_PRODUCT_PERFORMANCE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column S_DK_SUB_PORTFOLIO_ID
		dataType: string
		isHidden
		lineageTag: a72a33ea-5c54-4257-b6cb-460065c0fdb3
		summarizeBy: none
		sourceColumn: S_DK_SUB_PORTFOLIO_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column S_DK_PERFORMANCE_DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 6d6157a0-3fb0-469a-8955-46d1b68a7cfb
		summarizeBy: none
		sourceColumn: S_DK_PERFORMANCE_DATE

		variation Variasjon
			isDefault
			relationship: 0e64a3b5-86e0-4d29-bc28-e328ef2bcf18
			defaultHierarchy: LocalDateTable_f89fc23d-ea0b-48cf-be85-fff01a5153b6.Datohierarki

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column S_FK_DIM_SRE_PRODUCT
		dataType: string
		isHidden
		lineageTag: d32d59cb-77a4-4386-95dc-4d916319a640
		summarizeBy: none
		sourceColumn: S_FK_DIM_SRE_PRODUCT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_DATE_PERFORMANCE_DATE
		dataType: string
		isHidden
		lineageTag: 2e505722-bd0a-4221-9f4a-03d82ccbb308
		summarizeBy: none
		sourceColumn: S_FK_DIM_DATE_PERFORMANCE_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_CURRENCY
		dataType: string
		isHidden
		lineageTag: 0e926423-5c6f-4edd-a795-a18d9038d7fa
		summarizeBy: none
		sourceColumn: S_FK_DIM_CURRENCY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column S_FK_DIM_COUNTRY
		dataType: string
		isHidden
		lineageTag: ebd28899-041e-48f1-a912-df49a70aed8f
		summarizeBy: none
		sourceColumn: S_FK_DIM_COUNTRY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CHANGE_IN_VALUE_QUARTER
		dataType: double
		isHidden
		lineageTag: 48f03a08-380c-43a8-a4c1-d6aa386ab284
		summarizeBy: sum
		sourceColumn: CHANGE_IN_VALUE_QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DEBT FACT'
		dataType: double
		isHidden
		lineageTag: 807d3e7a-82c2-4f2c-9181-72a8b0429650
		summarizeBy: sum
		sourceColumn: DEBT FACT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIRECT_RETURN_QUARTER
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c2760298-af9f-4c4a-a7e0-342e40bdc943
		summarizeBy: sum
		sourceColumn: DIRECT_RETURN_QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DIRECT_RETURN_YEAR
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 6ffcfaaa-5159-4c2f-9e2f-1930f1becb11
		summarizeBy: sum
		sourceColumn: DIRECT_RETURN_YEAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ENTERPRISE_VALUE
		dataType: double
		isHidden
		lineageTag: 9c6f8068-15bb-4201-83dc-e1c6463c9dc9
		summarizeBy: sum
		sourceColumn: ENTERPRISE_VALUE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FINANCE_GAIN_LOSS_QUARTER
		dataType: double
		isHidden
		lineageTag: a7320de1-c1d6-4f6e-93b8-712e171945af
		summarizeBy: sum
		sourceColumn: FINANCE_GAIN_LOSS_QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PROFIT_LOSS_QUARTER
		dataType: double
		isHidden
		lineageTag: 90c2df9b-c2f8-46c6-ba70-2b88d128d4e0
		summarizeBy: sum
		sourceColumn: PROFIT_LOSS_QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TOTAL_RETURN_QUARTER
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 045d56e2-7157-4f12-9943-8f8a20749f4b
		summarizeBy: sum
		sourceColumn: TOTAL_RETURN_QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TOTAL_RETURN_YEAR
		dataType: double
		isHidden
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 126c2e87-055f-4136-a684-e8f126d7bf5b
		summarizeBy: sum
		sourceColumn: TOTAL_RETURN_YEAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VEK
		dataType: double
		isHidden
		lineageTag: e4c8e160-04ef-467f-9a8c-4123c1437d57
		summarizeBy: sum
		sourceColumn: VEK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_SRE_PRODUCT_PERFORMANCE = m
		mode: import
		source =
				let
				  Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com", "ANALYSIS_SAM_WH", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = "2.0"]),
				  #"Navigering 1" = Kilde{[Name = "DWH_SAM", Kind = "Database"]}[Data],
				  #"Navigering 2" = #"Navigering 1"{[Name = "REAL_ESTATE", Kind = "Schema"]}[Data],
				  #"Navigering 3" = #"Navigering 2"{[Name = "FACT_SRE_PRODUCT_PERFORMANCE", Kind = "View"]}[Data],
				    #"Kolonner med nye navn" = Table.RenameColumns(#"Navigering 3",{{"DEBT", "DEBT FACT"}})
				in
				  #"Kolonner med nye navn"

	changedProperty = Name

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

