table Product
	lineageTag: 65b1716e-ec44-40f5-8b09-d7a1bd949caf

	column S_PK_DIM_SRE_PRODUCT
		dataType: string
		isHidden
		lineageTag: d0a7d5ba-22a4-4af4-8dd7-43e41c3c73a1
		summarizeBy: none
		sourceColumn: S_PK_DIM_SRE_PRODUCT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Subportfolio ID'
		dataType: string
		lineageTag: aade2c9c-0026-41bd-9910-1aa2cc4a195f
		summarizeBy: none
		sourceColumn: Subportfolio ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 0b1beb03-4415-43e1-a45e-17bcc6f4de1e
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 85edd2b9-4bf9-4502-afdc-f98a3d894d69
		summarizeBy: none
		sourceColumn: Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Portfolio ID'
		dataType: string
		lineageTag: a2a8edd8-a00b-4fc7-8deb-1fba1fbd8cd8
		summarizeBy: none
		sourceColumn: Portfolio ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: c244ec87-984e-444f-978c-c437d28b058f
		summarizeBy: none
		sourceColumn: Product Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 4bf334b7-6f41-4438-9da0-da653690258c
		summarizeBy: none
		sourceColumn: Product Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Party ID'
		dataType: string
		lineageTag: 85ce8954-efda-448f-ac4b-1b6c20970462
		summarizeBy: none
		sourceColumn: Party ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SUB_PORTFOLIO_ID
		dataType: string
		isHidden
		lineageTag: 9c2d2147-ff19-4b66-a7b9-ca0754351365
		summarizeBy: none
		sourceColumn: SUB_PORTFOLIO_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				  Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com", "ANALYSIS_SAM_WH", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = "2.0"]),
				  #"Navigering 1" = Kilde{[Name = "DWH_SAM", Kind = "Database"]}[Data],
				  #"Navigering 2" = #"Navigering 1"{[Name = "REAL_ESTATE", Kind = "Schema"]}[Data],
				  #"Navigering 3" = #"Navigering 2"{[Name = "DIM_SRE_PRODUCT", Kind = "View"]}[Data],
				    #"Kolonner med nye navn" = Table.RenameColumns(#"Navigering 3",{{"COUNTRY", "Country"}, {"CURRENCY", "Currency"}, {"PORTFOLIO_ID", "Portfolio ID"}, {"PRODUCT_NAME", "Product Name"}, {"PRODUCT_TYPE", "Product Type"}, {"S_DK_SUB_PORTFOLIO_ID", "Subportfolio ID"}, {"SCD_PARTY_ID", "Party ID"}})
				in
				  #"Kolonner med nye navn"

	changedProperty = Name

	annotation PBI_ResultType = Table

