table Property
	lineageTag: 0a735f37-437f-4def-ae75-bf4f7b8e06df

	column S_PK_DIM_SRE_PROPERTY
		dataType: string
		isHidden
		lineageTag: a792a265-bffe-48b4-a35b-545c4eb99568
		summarizeBy: none
		sourceColumn: S_PK_DIM_SRE_PROPERTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Building ID'
		dataType: string
		lineageTag: fcdfef8b-8755-4dd0-a6f7-b865758f2469
		summarizeBy: none
		sourceColumn: Building ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 8a7fcf0c-cd83-4179-8688-150b8ccd836f
		summarizeBy: none
		sourceColumn: Address

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Parcel Number (Matrikkel Bruksnummer)'
		dataType: string
		lineageTag: 85bfc658-e3ad-4735-8ee6-d039e2daa125
		summarizeBy: none
		sourceColumn: Parcel Number (Matrikkel Bruksnummer)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Building Name'
		dataType: string
		lineageTag: c615670e-eda7-4e2e-b175-3cffa9c8fea7
		summarizeBy: none
		sourceColumn: Building Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Building Permit Name'
		dataType: string
		lineageTag: bd6c46e0-9a4c-4235-bbe7-881568fa87c8
		summarizeBy: none
		sourceColumn: Building Permit Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Constructed Year'
		dataType: string
		lineageTag: c299a0a1-589a-40bc-9bfa-749f801afbf7
		summarizeBy: none
		sourceColumn: Constructed Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 7882ea61-f8af-4255-bdb3-0730c215a918
		summarizeBy: none
		sourceColumn: Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Disposition Date'
		dataType: string
		lineageTag: 88013eeb-0655-46ac-8b6b-e845d37c0337
		summarizeBy: none
		sourceColumn: Disposition Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'External Building Number'
		dataType: string
		lineageTag: bde23fed-b7c4-4a11-b908-cd083fd7f171
		summarizeBy: none
		sourceColumn: External Building Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Farm Number (Matrikkel Gårdsnummer)'
		dataType: string
		lineageTag: 919c5acc-2223-4139-bccf-e67aab9a5b8c
		summarizeBy: none
		sourceColumn: Farm Number (Matrikkel Gårdsnummer)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Municipality Number'
		dataType: string
		lineageTag: db2333a9-866c-4b17-99ef-c3c2a774463c
		summarizeBy: none
		sourceColumn: Municipality Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: ec3e52a8-cecd-41d4-a1bf-916363598bb2
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Main Building Segment'
		dataType: string
		lineageTag: 1adf7dfc-4fb8-41c0-8c4f-ac36919b15a4
		summarizeBy: none
		sourceColumn: Main Building Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Owner Organisation Number'
		dataType: string
		lineageTag: f8743b51-acc1-4d7c-b1e4-947fe793ae81
		summarizeBy: none
		sourceColumn: Owner Organisation Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Plot Area'
		dataType: double
		lineageTag: 3b0f5493-5099-4a0d-9165-c6af9be94415
		summarizeBy: sum
		sourceColumn: Plot Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Postal Area'
		dataType: string
		lineageTag: 7e7e132e-79be-4662-8630-72a0a317d246
		summarizeBy: none
		sourceColumn: Postal Area

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Postal Number'
		dataType: string
		lineageTag: 868a3aed-c148-4f98-b8b3-2ceb5473a8d2
		summarizeBy: none
		sourceColumn: Postal Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Property Manager Name'
		dataType: string
		lineageTag: baa04778-f562-45ef-95dd-ec2f358071e4
		summarizeBy: none
		sourceColumn: Property Manager Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Property Manager'
		dataType: string
		lineageTag: df3f727d-3ffe-4321-8e37-81506330cc63
		summarizeBy: none
		sourceColumn: Property Manager

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Property Name'
		dataType: string
		lineageTag: 65f43945-bada-4b6e-98e2-1f69acdb60fa
		summarizeBy: none
		sourceColumn: Property Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Purchase Price'
		dataType: double
		lineageTag: f5a60662-dd32-451f-a01e-f8120d9278cf
		summarizeBy: sum
		sourceColumn: Purchase Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Section Number (Matrikkel Seksjonsnummer)'
		dataType: string
		lineageTag: 4a3d7f5c-9a3c-4760-a544-948a1dc7597d
		summarizeBy: none
		sourceColumn: Section Number (Matrikkel Seksjonsnummer)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Property ID'
		dataType: string
		lineageTag: 2956701b-6c38-42c7-a39e-2051e4c06b61
		summarizeBy: none
		sourceColumn: Property ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Acquired GFA'
		dataType: double
		lineageTag: 515f2714-1ccd-485e-a709-afd56d2c8ee4
		summarizeBy: sum
		sourceColumn: Acquired GFA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Acquisition Date'
		dataType: string
		lineageTag: 02e0cf19-a484-4316-9dfe-85830b02d787
		summarizeBy: none
		sourceColumn: Acquisition Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Subportfolio ID'
		dataType: string
		lineageTag: e3c945f9-4451-4191-a7ae-d7c9fbb1da92
		summarizeBy: none
		sourceColumn: Subportfolio ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Property = m
		mode: import
		source =
				let
				    Kilde = Snowflake.Databases("cb20535.west-europe.azure.snowflakecomputing.com","ANALYSIS_SAM_WH",[Implementation="2.0"]),
				    DWH_SAM_Database = Kilde{[Name="DWH_SAM",Kind="Database"]}[Data],
				    REAL_ESTATE_Schema = DWH_SAM_Database{[Name="REAL_ESTATE",Kind="Schema"]}[Data],
				    DIM_SRE_PROPERTY_View = REAL_ESTATE_Schema{[Name="DIM_SRE_PROPERTY",Kind="View"]}[Data],
				    #"Kolonner med nye navn" = Table.RenameColumns(DIM_SRE_PROPERTY_View,{{"ACQUIRED_GFA", "Acquired GFA"}, {"ACQUISITION_DATE", "Acquisition Date"}, {"ADDRESS", "Address"}, {"B_NO", "Parcel Number (Matrikkel Bruksnummer)"}, {"BUILDING_NAME", "Building Name"}, {"BUILDING_PERMIT_DATE", "Building Permit Name"}, {"CONSTRUCTED_YEAR", "Constructed Year"}, {"CURRENCY", "Currency"}, {"DISPOSITION_DATE", "Disposition Date"}, {"EXTERNAL_BUILDING_NO", "External Building Number"}, {"G_NO", "Farm Number (Matrikkel Gårdsnummer)"}, {"K_NO", "Municipality Number"}, {"LOCATION", "Location"}, {"MAIN_BUILDING_SEGMENT", "Main Building Segment"}, {"OWNER_ORG_NO", "Owner Organisation Number"}, {"PLOT_AREA", "Plot Area"}, {"POSTAL_AREA", "Postal Area"}, {"POSTAL_NO", "Postal Number"}, {"PROPERTY_ID", "Property ID"}, {"PROPERTY_MANAGER", "Property Manager"}, {"PROPERTY_MANAGER_NAME", "Property Manager Name"}, {"PROPERTY_NAME", "Property Name"}, {"PURCHASE_PRICE", "Purchase Price"}, {"S_DK_BUILDING_ID", "Building ID"}, {"S_NO", "Section Number (Matrikkel Seksjonsnummer)"}, {"SUB_PORTFOLIO_ID", "Subportfolio ID"}})
				in
				    #"Kolonner med nye navn"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigasjon

